---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Login
      uri:
         url: "https://{{ mgmt_server }}/web_api/login"
         validate_certs: false
         method: POST
         body: 
           user: "{{ mgmt_user }}"
           password: "{{ mgmt_password }}"       
         body_format: json   
      register: loginoutput

    - set_fact:
         sid: "{{ loginoutput.json.sid }}"

    - name: Add Host 
      uri:
         url: "https://{{ mgmt_server }}/web_api/add-host"
         validate_certs: false
         method: POST
         body:
           name: "native_host"
           ip-address: "5.4.3.2"
           set-if-exists: true
           color: blue
           host-servers:
             dns-server: false
         body_format: json
         headers :
           X-chkp-sid : "{{ sid }}"

    - name: Publish
      uri:
         url: "https://{{ mgmt_server }}/web_api/publish"
         validate_certs: false
         method: POST
         body_format: json
         body: "{}"
         headers :
           X-chkp-sid : "{{ sid }}"
      register: taskid

    - set_fact:
         task: "{{ taskid.json['task-id'] }}"

    - name: Check Task Progress Status
      uri:
         url: "https://{{ mgmt_server }}/web_api/show-task"
         validate_certs: false
         method: POST
         body_format: json
         body: 
           task-id: "{{ task }}"    
         headers:
           X-chkp-sid : "{{ sid }}"
      retries: 20
      delay: 3
      register: taskoutput
      until: (taskoutput.json.tasks[0]['progress-percentage'] == 100)
      failed_when:
        - (taskoutput.json.tasks[0]['progress-percentage'] == 100)
        - (taskoutput.json.tasks[0]['status'] != "succeeded")

    - name: Logout
      uri:
         url: "https://{{ mgmt_server }}/web_api/logout"
         validate_certs: false
         method: POST
         body_format: json
         body: "{}"
         headers :
           X-chkp-sid : "{{ sid }}"
