---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Login
      uri:
         url: "https://{{ cpx_gw_ip }}/gaia_api/login"
         validate_certs: false
         method: POST
         body: 
           user: "{{ gaia_user }}"
           password: "{{ gaia_password }}"       
         body_format: json   
      register: loginoutput

    - set_fact:
         sid: "{{ loginoutput.json.sid }}"

    - name: Set Gateway  
      uri:
         url: "https://{{ cpx_gw_ip }}/gaia_api/set-physical-interface"
         validate_certs: false
         method: POST
         body:
            name: "eth1"
            enabled: "true"
            comments: "Gaia API set on Eth1"
         body_format: json
         headers :
           X-chkp-sid : "{{ sid }}"

    - name: Logout
      uri:
         url: "https://{{ cpx_gw_ip }}/gaia_api/logout"
         validate_certs: false
         method: POST
         body_format: json
         body: "{}"
         headers :
           X-chkp-sid : "{{ sid }}"
