---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Login
      uri:
         url: "https://{{ mgmt_server }}/gaia_api/login"
         validate_certs: false
         method: POST
         body: 
           user: "{{ mgmt_user }}"
           password: "{{ mgmt_password }}"       
         body_format: json   
      register: loginoutput

    - set_fact:
         sid: "{{ loginoutput.json.sid }}"

    
    # - name: show-hostname
    #   uri:
    #      url: "https://{{ mgmt_server }}/gaia_api/show-version"
    #      validate_certs: false
    #      method: POST         
    #      body_format: json   
    #      headers :
    #        X-chkp-sid : "{{ sid }}"
    #   register: showhostname


    # - name: Publish
    #   uri:
    #      url: "https://{{ mgmt_server }}/web_api/publish"
    #      validate_certs: false
    #      method: POST
    #      body_format: json
    #      body: "{}"
    #      headers :
    #        X-chkp-sid : "{{ sid }}"
    #   register: taskid

    - set_fact:
         task: "{{ taskid.json['task-id'] }}"

    
    - name: Logout
      uri:
         url: "https://{{ mgmt_server }}/gaia_api/logout"
         validate_certs: false
         method: POST
         body_format: json
         body: "{}"
         headers :
           X-chkp-sid : "{{ sid }}"
