---
- hosts: "localhost"
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "admin"
        password: "vpn123"
        management: "203.0.113.81"
      context: "gaia_api"
      api_version: 1.4
      fingerprint: "18C9EDAF8887933CA129F486945D1DF377E5C4D0"
    register: login_response

  - name: "set physical interface"
    check_point_mgmt:
      command: set-physical-interface
      parameters:
        name: "eth1"
        enabled: "true"
      session-data: "{{ login_response }}"
    register: set_interface

  - debug:
      msg: "Interface output {{ set_interface }}"

  - name: "show dns"
    check_point_mgmt:
      command: show-dns
      session-data: "{{ login_response }}"
    register: dns

  - debug:
      msg: "DNS output {{ dns }}"

  - name: "show route"
    check_point_mgmt:
      command: show-routes
      session-data: "{{ login_response }}"
    register: routes

  - debug:
      msg: "Route output {{ routes }}"

