---
- name: My demo playbook
  hosts: MGMT
  connection: httpapi
  gather_facts: no

  # vars: 
  #   ansible_checkpoint_domain: "Main"

  tasks:
    - name: Gateway name
      debug: msg="just a test"

    - name: task to have network
      check_point.mgmt.cp_mgmt_network:
      #cp_mgmt_network:
        name: "net_4.1.80.0_m24"
        subnet: "4.1.80.0"
        mask_length: 24 
        #state: absent 
        state: present
        comments: "Test network created from Ansible via WEB API"
        auto_publish_session: true
 

  # Activate the tasks below for further tests. 


  #   - name: Add or delete policy package
  #     cp_mgmt_package:
  #       state: absent
  #       access: true
  #       color: blue
  #       comments: Policy automated through ansible and versioned in Git
  #       name: automation_policy
  #       threat_prevention: true

  #   - name: Add, set or delete Check Point host object
  #     cp_mgmt_host:
  #       state: absent
  #       name: Mail server
  #       ip_address: 192.168.1.1
  #       color: sea green
  #       comments: my mail server host objects

  #   - name: Add, set or delete Check Point host object
  #     cp_mgmt_host:
  #       state: absent
  #       name: Web server
  #       ip_address: 10.1.1.55
  #       color: yellow
  #       comments: my blue jump host object

  #   - name: Add, set or delete Check Point host object
  #     cp_mgmt_host:
  #       state: absent
  #       name: DB server
  #       ip_address: 10.1.2.55
  #       color: blue
  #       comments: my ubuntu host object

  #   - name: add-group, set or delete Check Point group object
  #     cp_mgmt_group:
  #       state: absent
  #       name: Ansible control node group
  #       color: forest green

  #   - name: add, set, or delete Check Point access rule
  #     cp_mgmt_access_rule:
  #       state: absent
  #       layer: automation_policy Network
  #       name: allow access from ansible control node
  #       position: 1
  #       source: Ansible control node group
  #       destination:
  #       - Web server
  #       - Mail server
  #       service:
  #       - http
  #       - https
  #       - ssh
  #       action: Accept
  #       track:
  #         type: log

  #   - name: add, set, or delete Check Point access rule
  #     cp_mgmt_access_rule:
  #       state: absent
  #       layer: automation_policy Network
  #       name: allow SMTP access from any where
  #       position: 2
  #       destination:
  #       - mail server
  #       service:
  #       - smtp
  #       action: Accept
  #       track:
  #         type: log

  #   - name: present
  #     cp_mgmt_publish: